openapi: 3.0.0
info:
  title: kb2 API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check
      description: Returns API health status
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
